APPS-2968: library also should update annotation of method that updat…
spryker/propel-encryption-behavior pull request #3
Opened 2022-01-26 09:15 UTC by olehnovatskyi-spryker

- Developer(s): @oleh.novatskyi 

- Ticket: [APPS-2968](https://spryker.atlassian.net/browse/APPS-2968)

- merge: merge

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   PropelEncryptionBehavior | patch                 |                       |

-----------------------------------------

#### Module PropelEncryptionBehavior

##### Change log

Fixes

- Adjusted `EncryptionBehavior::addEncryptionToSetter()` so it updates annotation for for setter method of the column with `BLOB` type. Now they receive `string` instead of `resource`.
- Adjusted `EncryptionBehavior::addDecryptionToGetter()` so it updates annotation for for getter method of the column with `BLOB` type. Now they return `string` instead of `resource`.

2022-01-26 14:37 UTC, kopylets commented on src/EncryptionBehavior.php
> +            $paramAnnotationLocation = strpos($script, 'param resource', $setterLocation - 300);
Perhaps we should implement a method that finds the nearest previous '}' before the name of the method, in order to accurately determine the phpdoc in which wehave to make a replacement.

2022-01-26 14:39 UTC, dereuromark commented on src/EncryptionBehavior.php
> +        string &$script,
Why &?
If possible we should not pass vars this way.

2022-01-26 15:16 UTC, oleksander-kiiashko commented on src/EncryptionBehavior.php
> +        string &$script,
Why do we need argument &$script, not just $script?

2022-01-26 16:03 UTC, oleksander-kiiashko approved these changes

2022-01-26 16:16 UTC, kopylets approved these changes

2022-01-27 06:16 UTC, stereomon commented on src/EncryptionBehavior.php
> +            $hasColumnBlobType = $column->getType() === PropelTypes::BLOB;
IMO it should be `$isBlobTypeColumn`.

2022-01-27 06:17 UTC, stereomon requested changes
We should have tests for this. Can you please add some?

2022-01-27 12:15 UTC, dereuromark commented on src/EncryptionBehavior.php
> +            $hasColumnBlobType = $column->getType() === PropelTypes::BLOB;
Please reread the suggestion

2022-01-27 12:15 UTC, dereuromark commented on src/EncryptionBehavior.php
> +            $hasColumnBlobType = $column->getType() === PropelTypes::BLOB;
Mainly about not using Yoga speak:)

2022-01-27 13:13 UTC, dereuromark commented
If this is supposed to be released, we should also see a changelog as per normal guidelines.

2022-01-27 13:22 UTC, olehnovatskyi-spryker commented
> If this is supposed to be released, we should also see a release template + changelog as per normal guidelines.

Ok, I will prepare it.

2022-01-27 13:42 UTC, stereomon approved these changes
Code wise ok for me now. Please add the release template as mentioned by @dereuromark

2022-01-27 15:54 UTC, olehnovatskyi-spryker commented
@dereuromark I added the template and changelogs. Check it, please.

2022-01-27 16:44 UTC, dereuromark commented
Almost, please use code fencing instead of bold for Code pieces etc.

2022-01-27 16:48 UTC, olehnovatskyi-spryker commented
Done

2022-01-27 16:50 UTC, merged

2022-01-27 16:54 UTC, olehnovatskyi-spryker commented
Are we going to have a new release tag?

2022-01-27 20:53 UTC, dereuromark commented
For the future it helps if you add the release link (with template check for validity) in the PR template for standalone packages (not going through RG release process).